In [1]:
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
# from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Lambda
from keras.utils import to_categorical
import matplotlib.pyplot as plt

In [2]:
(x_train_load, y_train_load), (x_test_load, y_test_load) = mnist.load_data()
# 處理數據
x_train_load = x_train_load[:500]
y_train_load = y_train_load[:500]

x_test_load = x_test_load[:20]
y_test_load = y_test_load[:20]

print(x_test_load.shape)
print(y_test_load)


(20, 28, 28)
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


In [5]:
# Data normalization

# x_train = x_train_load.reshape((x_train_load.shape[0], 28, 28, 1)).astype('float32') / 255     # ==> 39s
# x_test = x_test_load.reshape((x_test_load.shape[0], 28, 28, 1)).astype('float32') / 255
x_train = x_train_load.reshape((x_train_load.shape[0], 28, 28, 1))                        # ==> 37s  43
x_test = x_test_load.reshape((x_test_load.shape[0], 28, 28, 1))

# 將標籤轉換為 one-hot 編碼
y_train = to_categorical(y_train_load)
y_test = to_categorical(y_test_load)
print(x_test.shape)
print(y_test)


(20, 28, 28, 1)
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [6]:

# # # 建立一個ImageDataGenerator實例
# datagen = ImageDataGenerator(rescale=1./255)

# # # 使用.flow_from_directory()方法從目錄中載入圖像
# train_generator = datagen.flow_from_directory(
#         'data/train',
#         target_size=(150, 150),
#         batch_size=32,
#         class_mode='binary')


In [7]:
from keras.preprocessing.image import ImageDataGenerator
# 創建圖像數據生成器
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,  # 隨機旋轉的角度範圍
    zoom_range=0.1,  # 隨機縮放的範圍
    width_shift_range=0.1,  # 水平移動的範圍
    height_shift_range=0.1  # 垂直移動的範圍
)

# 適用生成器於訓練數據
train_generator = train_datagen.flow(x_train, y_train)

# ....

# history = model.fit(train_generator, epochs=50, batch_size=64, validation_data=(x_test, y_test))


In [ ]:
# 建立模型
import time
start_time = time.time()


model = Sequential()
model.add(Lambda(lambda x: x / 255))    
model.add(Conv2D(8, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(16, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(16, (3, 3), activation='relu'))
model.add(Flatten())
model.add(Dense(16, activation='relu'))
model.add(Dense(10, activation='softmax'))

# 編譯模型   !!! try to change one-hot to categorical input
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# 訓練模型   
history = model.fit(x_train, y_train, epochs=50, batch_size=64, validation_data=(x_test, y_test))
# history = model.fit(train_generator, epochs=50, batch_size=64, validation_data=(x_test, y_test))
end_time = time.time()
print(f"Training took {end_time - start_time} seconds")


In [ ]:
y = lambda x: x / 255
print(y(5))  # 輸出: 10

In [ ]:
double = lambda x: x * 2
print(double(5))  # 輸出: 10

## Lambda 函數的基本語法：

lambda arguments: expression
這裡，arguments 是函數的參數列表，expression 是函數體，它是基於這些參數的表達式，lambda 函數會返回該表達式的結果。

範例 1：單一參數的 Lambda 函數
double = lambda x: x * 2
print(double(5))  # 輸出: 10

範例 2：多個參數的 Lambda 函數
multiply = lambda x, y: x * y
print(multiply(2, 3))  # 輸出: 6

範例 3：搭配條件表達式的 Lambda 函數
max = lambda x, y: x if x > y else y
print(max(5, 7))  # 輸出: 7

Lambda 函數由於其簡潔性，特別適合於需要快速、臨時使用小函數的場合。不過，如果函數的邏輯較為複雜，或者需要多次重用，建議使用標準的函數定義方式（使用 def 關鍵字）。

In [ ]:
from sklearn.metrics import confusion_matrix

y_pred = model.predict(x_train)
y_pred_label = np.argmax(y_pred, axis=1)
y_train_label = np.argmax(y_train, axis=1)
cm = confusion_matrix(y_train_label, y_pred_label)

# 打印混淆矩陣
print("Confusion Matrix:")
print(cm)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# 繪製混淆矩陣的熱圖
plt.figure(figsize=(10, 7))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

## Exercise : try to encapsulate the confusion matrix functionality and utilize it to present the results of both training set and testing set

In [ ]:
import matplotlib.pyplot as plt

plt.plot(history.history['loss'], 'r', label='Training loss')
plt.plot(history.history['val_loss'], 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()


In [ ]:
# 評估模型
test_loss, test_acc = model.evaluate(x_test, y_test)
print('Test accuracy:', test_acc)

In [ ]:
y_pred = model.predict(x_test)
print(y_pred.shape)

# print(|y_pred)
y_pred_label = np.argmax(y_pred, axis=1)    
print('y_pred: ', y_pred_label)


In [ ]:
# 找出預測錯誤的索引
y_pred = model.predict(x_test)
print('y_shape: ', y_pred.shape)

y_pred_label = np.argmax(y_pred, axis=1)  # axis=1：沿著行查找每行的最大值的索引。axis=0：沿著列查找每列的最大值的索引。
y_test_label = np.argmax(y_test, axis=1)

print('y_pred: ', y_pred_label)
print('y_test: ', y_test_label)

len(x_test)
errors = np.where(y_pred_label != y_test_label)[0]
print(f'Index of Prediction errors:  {errors} ')
print(f'Total number of prediction errors: {len(errors)}')

## Exercise : Try to visualize the wrong predictions

In [ ]:
# 使用 matplotlib 顯示多張圖像
# 設置圖像數量

num_images = len(errors)

# 創建一個圖形和一組子圖
fig, axes = plt.subplots(1, num_images, figsize=(10, 10))

for i, ax in enumerate(axes):
    # 顯示第 i 張圖像
    ax.imshow(x_test_load[errors[i]])
    ax.set_title(f'Label: {y_pred_label[errors[i]]}')
    ax.axis('off')  # 不顯示軸

plt.tight_layout()
plt.show()