In [2]:

import numpy as np
import pandas as pd
import scipy.io

XYZ_Coord = scipy.io.loadmat('data\XYZcoord1.mat')
XYZ_C = np.array(XYZ_Coord ['XYZ1'])
XYZ_C
print(len(XYZ_C))
print(XYZ_C)

import math as mt
import random as rd

#預先定義歐是距離函數
def dist(a,b):
    r2 = (a[0]-b[0])**2+(a[1]-b[1])**2+(a[2]-b[2])**2
    r = mt.sqrt(r2)
    return r
#先設一個list 來存放點對點歐式距離的結果與資訊
Euclidean_Edges=[0,0,0]

for i in range(1990,1995):  #從第一點到倒數第二點計算
    p1=XYZ_C[i]
    for j in range(i+1,len(XYZ_C)-1):
        p2=XYZ_C[j]
        source=i
        Target=j
        Weight=dist(p1,p2)
        pp=[source,Target,Weight]
        Euclidean_Edges=np.vstack((Euclidean_Edges,pp))
print(Euclidean_Edges)



2000
[[ 0.6851533   1.17897583  3.52402492]
 [ 1.00216962  1.21572705 29.32701994]
 [ 1.15125728  3.32476951 23.614195  ]
 ...
 [90.13576705 15.58773776 34.16825421]
 [90.73121678 16.76765189 13.4218382 ]
 [89.09981586 18.50040944 13.39066304]]
[[   0.            0.            0.        ]
 [1990.         1991.           22.309621  ]
 [1990.         1992.           13.86491392]
 [1990.         1993.           11.66889445]
 [1990.         1994.           20.26599121]
 [1990.         1995.           22.19431704]
 [1990.         1996.           19.10742307]
 [1990.         1997.            9.80718966]
 [1990.         1998.           12.94068655]
 [1991.         1992.            8.45461044]
 [1991.         1993.           10.86650845]
 [1991.         1994.            2.55244555]
 [1991.         1995.            2.92466907]
 [1991.         1996.            6.23355516]
 [1991.         1997.           31.38323101]
 [1991.         1998.           11.36444709]
 [1992.         1993.            2.